### ISSUE TITLE
Panic in version 1.1.1

### ISSUE THREAD

**Issue by Melvin-Ross-PillPack** [awslabs/aws-cloudformation-template-formatter#11]
I get the following panic when I run the latest version. Version 1.1.0 does not panic and returns the formatted yaml

```panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/aws-cloudformation/rain/cfn.findRefs(0xc00015a2d0, 0xc00015a2d0, 0xc000086380, 0x1)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/tree.go:43 +0xbed
github.com/aws-cloudformation/rain/cfn.findRefs(0xc00015a270, 0xc000141080, 0xc000062dc0, 0x5)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/tree.go:51 +0xae9
github.com/aws-cloudformation/rain/cfn.findRefs(0xc00015a240, 0xc00015a240, 0xc000086348, 0x1)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/tree.go:51 +0xae9
github.com/aws-cloudformation/rain/cfn.findRefs(0xc00015a1e0, 0xc00015a1e0, 0xc000086338, 0x1)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/tree.go:51 +0xae9
github.com/aws-cloudformation/rain/cfn.findRefs(0xc00015a1b0, 0x11713e0, 0xc0001417e0, 0x0)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/tree.go:51 +0xae9
github.com/aws-cloudformation/rain/cfn.getRefs(...)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/tree.go:12
github.com/aws-cloudformation/rain/cfn.Template.Graph(0xc00013d8c0, 0xc00013d8c0, 0x0, 0x0, 0x0)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/cfn.go:74 +0x62d
github.com/aws-cloudformation/rain/cfn/format.(*encoder).sortKeys(0xc000117a80, 0x131fd98, 0x0, 0xc000117958)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/format/sort.go:122 +0x8dd
github.com/aws-cloudformation/rain/cfn/format.encoder.formatMap(0x0, 0x0, 0x0, 0x1171480, 0xc00013d8c0, 0x0, 0xc0001438b0, 0x1, 0x1, 0x1164980, ...)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/format/encoder.go:104 +0x60
github.com/aws-cloudformation/rain/cfn/format.encoder.format(0x0, 0x0, 0x0, 0x1171480, 0xc00013d8c0, 0x0, 0xc0001438b0, 0x1, 0x1, 0x1164980, ...)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/format/encoder.go:236 +0x22d
github.com/aws-cloudformation/rain/cfn/format.encoder.formatMap(0x0, 0x0, 0x0, 0x1171480, 0xc00013d8c0, 0x0, 0xc0001438b0, 0x1, 0x1, 0x1164980, ...)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/format/encoder.go:112 +0x1f1
github.com/aws-cloudformation/rain/cfn/format.encoder.format(0x0, 0x0, 0x0, 0x1171480, 0xc00013d8c0, 0x0, 0x12d8ed8, 0x0, 0x0, 0x1171480, ...)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/format/encoder.go:234 +0x40c
github.com/aws-cloudformation/rain/cfn/format.Template(0xc00013d8c0, 0x0, 0xc00013d800, 0x0, 0x0, 0x2ba8)
	/home/steve/.gohome/pkg/mod/github.com/aws-cloudformation/rain@v0.7.1/cfn/format/format.go:36 +0xd0
main.main()
	/home/steve/code/github.com/awslabs/aws-cloudformation-template-formatter/cmd/cfn-format/main.go:96 +0x1d1 ```

**Comment by stilvoid** [comment]
@Melvin-Ross-PillPack Could you paste an example of something that causes this panic?

**Comment by Melvin-Ross-PillPack** [comment]
I didn't get alerted when you posted this comment. I don't know why I didn't post a reproducer in the first place.... I'll try and put one together and get back to you

**Comment by ctd** [comment]
Closing this out for inactivity.

You're welcome to re-open this issue when/if you're able to reproduce the error.
